### ISSUE TITLE
Current user archives disappear if user follows him/herself

### ISSUE THREAD

**Issue by d4tocchini** [beakerbrowser/beaker-virtual-fs#1]
Ran into an edge case with beaker-0.8

If currentUser follows currentUser then all archives other than `FSVirtualFolder_User`s archives are ignored.

Traced it down to a simple case where `FSVirtualRoot:readChildren` registers an additional  `FSVirtualFolder_User` node without the `isCurrentUser` set to true.  Will submit a PR...

**Comment by pfrazee** [comment]
Thanks for the fix!
